#api_key: sk-33025c4ffca341b28fbcb6ed9d6ac3d4
base_url: https://api.deepseek.com/v1
input_file: ./test/test.pdf
model_name: deepseek-v4-flash
model_type: OpenAIModel
output_format: pdf
source_language: English
target_language: Chinese
